/********************************************************************
* DictOutput.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DictOutput.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevDictOutput();
extern G__DLLEXPORT void G__set_cpp_environmentDictOutput();
extern G__DLLEXPORT void G__cpp_setup_tagtableDictOutput();
extern G__DLLEXPORT void G__cpp_setup_inheritanceDictOutput();
extern G__DLLEXPORT void G__cpp_setup_typetableDictOutput();
extern G__DLLEXPORT void G__cpp_setup_memvarDictOutput();
extern G__DLLEXPORT void G__cpp_setup_globalDictOutput();
extern G__DLLEXPORT void G__cpp_setup_memfuncDictOutput();
extern G__DLLEXPORT void G__cpp_setup_funcDictOutput();
extern G__DLLEXPORT void G__cpp_setupDictOutput();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sct/axis.hh"
#include "sct/collection.h"
#include "sct/EUTFile.h"
#include "sct/generic_plane.hh"
#include "sct/processor.h"
#include "sct/ProcessorCollection.h"
#include "sct\xy_processors\processorPlaneVSPlane.h"
#include "sct\predef\hit.hh"
#include "sct\predef\plane.hh"
#include "sct\lagacy\setup_description.hh"
#include "sct\lagacy\s_cuts.h"
#include "sct\lagacy\xml_input_file.hh"
#include "sct\lagacy\Draw.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictOutputLN_TObject;
extern G__linked_taginfo G__DictOutputLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__DictOutputLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__DictOutputLN_string;
extern G__linked_taginfo G__DictOutputLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictOutputLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictOutputLN_ProcessorCollection;
extern G__linked_taginfo G__DictOutputLN_TTree;
extern G__linked_taginfo G__DictOutputLN_axis;
extern G__linked_taginfo G__DictOutputLN_generic_plane;
extern G__linked_taginfo G__DictOutputLN_processor_prob;
extern G__linked_taginfo G__DictOutputLN_SaveOption;
extern G__linked_taginfo G__DictOutputLN_collection;
extern G__linked_taginfo G__DictOutputLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_iteratorlErandom_access_iterator_tagcOstringcOlongcOstringmUcOstringaNgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictOutputLN_TFile;
extern G__linked_taginfo G__DictOutputLN_EUTFile;
extern G__linked_taginfo G__DictOutputLN_init_returns;
extern G__linked_taginfo G__DictOutputLN_process_returns;
extern G__linked_taginfo G__DictOutputLN_end_returns;
extern G__linked_taginfo G__DictOutputLN_processor;
extern G__linked_taginfo G__DictOutputLN_hit;
extern G__linked_taginfo G__DictOutputLN_fitterHit;
extern G__linked_taginfo G__DictOutputLN_plane;
extern G__linked_taginfo G__DictOutputLN_xy_plane;
extern G__linked_taginfo G__DictOutputLN_FitterPlane;
extern G__linked_taginfo G__DictOutputLN_processorPlaneVSPlane;
extern G__linked_taginfo G__DictOutputLN_rapid_xml_node;
extern G__linked_taginfo G__DictOutputLN_Xladder;
extern G__linked_taginfo G__DictOutputLN_Xsensitive;
extern G__linked_taginfo G__DictOutputLN_Xlayer;
extern G__linked_taginfo G__DictOutputLN_Xdetector;
extern G__linked_taginfo G__DictOutputLN_vectorlEXlayercOallocatorlEXlayergRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEXlayercOallocatorlEXlayergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_iteratorlErandom_access_iterator_tagcOXlayercOlongcOXlayermUcOXlayeraNgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEXlayercOallocatorlEXlayergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictOutputLN_XBField;
extern G__linked_taginfo G__DictOutputLN_Xgear;
extern G__linked_taginfo G__DictOutputLN_S_Cut;
extern G__linked_taginfo G__DictOutputLN_S_NoCut;
extern G__linked_taginfo G__DictOutputLN_S_Cut_min_max;
extern G__linked_taginfo G__DictOutputLN_S_XCut;
extern G__linked_taginfo G__DictOutputLN_S_YCut;
extern G__linked_taginfo G__DictOutputLN_S_Cut_BinContent;
extern G__linked_taginfo G__DictOutputLN_S_CutCoollection;
extern G__linked_taginfo G__DictOutputLN_MinMaxRange;
extern G__linked_taginfo G__DictOutputLN_xml_globalConfig;
extern G__linked_taginfo G__DictOutputLN_xml_file;
extern G__linked_taginfo G__DictOutputLN_XML_imput_file;
extern G__linked_taginfo G__DictOutputLN_vectorlExml_filecOallocatorlExml_filegRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlExml_filecOallocatorlExml_filegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_iteratorlErandom_access_iterator_tagcOxml_filecOlongcOxml_filemUcOxml_fileaNgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlExml_filecOallocatorlExml_filegRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__DictOutputLN_TCut;
extern G__linked_taginfo G__DictOutputLN_DrawOption;

/* STUB derived class for protected member access */
